language: ruby
sudo: false
cache: bundler
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - jruby-9.0.1.0
matrix:
  include:
    - rvm: jruby
      gemfile: gemfiles/rails_4.2.gemfile
      env: JRUBY_OPTS="--2.0"
    - rvm: 2.2.3
      gemfile: gemfiles/rails_head.gemfile
  allow_failures:
    - gemfile: gemfiles/rails_head.gemfile
